modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "island_world"
version = "${version}"
displayName = "Island World"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''

# A file name (in the root of the mod JAR) containing a logo for display
logoFile= "island_world_logo.png"

[[dependencies.island_world]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.island_world]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.island_world]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "island_world.mixins.json"
